"""initial normalized schema

Revision ID: f3ce06ac6486
Revises:
Create Date: 2026-07-24 20:25:08.774047
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f3ce06ac6486"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("normalized_payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_records")),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("original_question", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    op.create_table(
        "briefs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("final_qa_status", sa.String(length=32), nullable=False),
        sa.Column("aggregate_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_briefs_question_id_questions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_briefs")),
    )
    with op.batch_alter_table("briefs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_briefs_question_id"), ["question_id"], unique=False)
    op.create_table(
        "ontology_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("original_term", sa.Text(), nullable=False),
        sa.Column("normalized_term", sa.Text(), nullable=False),
        sa.Column("ontology", sa.String(length=32), nullable=False),
        sa.Column("selected_code", sa.String(length=64), nullable=True),
        sa.Column("match_method", sa.String(length=64), nullable=False),
        sa.Column("human_review_required", sa.Boolean(), nullable=False),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_ontology_mappings_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ontology_mappings")),
    )
    with op.batch_alter_table("ontology_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ontology_mappings_question_id"), ["question_id"], unique=False
        )

    op.create_table(
        "pico_elements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("element_type", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_pico_elements_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pico_elements")),
        sa.UniqueConstraint("question_id", "element_type", "position", name="uq_pico_position"),
    )
    with op.batch_alter_table("pico_elements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pico_elements_question_id"), ["question_id"], unique=False
        )

    op.create_table(
        "trials",
        sa.Column("evidence_record_id", sa.Integer(), nullable=False),
        sa.Column("overall_status", sa.String(length=64), nullable=False),
        sa.Column("study_type", sa.String(length=64), nullable=False),
        sa.Column("allocation", sa.String(length=64), nullable=True),
        sa.Column("enrollment", sa.Integer(), nullable=True),
        sa.Column("has_results", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_trials_evidence_record_id_evidence_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("evidence_record_id", name=op.f("pk_trials")),
    )
    op.create_table(
        "brief_evidence",
        sa.Column("brief_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_record_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("ranking_components", sa.JSON(), nullable=True),
        sa.Column("ranking_method", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["briefs.id"],
            name=op.f("fk_brief_evidence_brief_id_briefs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_brief_evidence_evidence_record_id_evidence_records"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("brief_id", "evidence_record_id", name=op.f("pk_brief_evidence")),
    )
    op.create_table(
        "brief_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("brief_id", sa.String(length=36), nullable=False),
        sa.Column("version_kind", sa.String(length=16), nullable=False),
        sa.Column("clinical_question", sa.Text(), nullable=False),
        sa.Column("executive_answer", sa.Text(), nullable=False),
        sa.Column("evidence_summary", sa.Text(), nullable=False),
        sa.Column("clinical_interpretation", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("draft_payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["briefs.id"],
            name=op.f("fk_brief_versions_brief_id_briefs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brief_versions")),
        sa.UniqueConstraint("brief_id", "version_kind", name="uq_brief_version_kind"),
    )
    with op.batch_alter_table("brief_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_brief_versions_brief_id"), ["brief_id"], unique=False)

    op.create_table(
        "exported_artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("brief_id", sa.String(length=36), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("storage_reference", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["briefs.id"],
            name=op.f("fk_exported_artifacts_brief_id_briefs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exported_artifacts")),
    )
    with op.batch_alter_table("exported_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exported_artifacts_brief_id"), ["brief_id"], unique=False
        )

    op.create_table(
        "llm_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("brief_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["briefs.id"],
            name=op.f("fk_llm_runs_brief_id_briefs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_runs")),
    )
    with op.batch_alter_table("llm_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_runs_brief_id"), ["brief_id"], unique=False)

    op.create_table(
        "ontology_candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mapping_id", sa.Integer(), nullable=False),
        sa.Column("ontology", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("preferred_label", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_id"],
            ["ontology_mappings.id"],
            name=op.f("fk_ontology_candidates_mapping_id_ontology_mappings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ontology_candidates")),
        sa.UniqueConstraint("mapping_id", "source_rank", name="uq_candidate_rank"),
    )
    with op.batch_alter_table("ontology_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ontology_candidates_mapping_id"), ["mapping_id"], unique=False
        )

    op.create_table(
        "searches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("brief_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("page_size", sa.Integer(), nullable=False),
        sa.Column("offset", sa.Integer(), nullable=True),
        sa.Column("page_token", sa.Text(), nullable=True),
        sa.Column("next_page_token", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["briefs.id"],
            name=op.f("fk_searches_brief_id_briefs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_searches")),
    )
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_searches_brief_id"), ["brief_id"], unique=False)

    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("brief_version_id", sa.Integer(), nullable=False),
        sa.Column("claim_key", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("claim_type", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["brief_version_id"],
            ["brief_versions.id"],
            name=op.f("fk_claims_brief_version_id_brief_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
        sa.UniqueConstraint("brief_version_id", "claim_key", name="uq_version_claim_key"),
    )
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_claims_brief_version_id"), ["brief_version_id"], unique=False
        )

    op.create_table(
        "qa_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("brief_id", sa.String(length=36), nullable=False),
        sa.Column("llm_run_id", sa.Integer(), nullable=False),
        sa.Column("report_kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reviewed_draft_sha256", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["briefs.id"],
            name=op.f("fk_qa_reports_brief_id_briefs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["llm_run_id"],
            ["llm_runs.id"],
            name=op.f("fk_qa_reports_llm_run_id_llm_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_reports")),
        sa.UniqueConstraint("brief_id", "report_kind", name="uq_brief_report_kind"),
    )
    with op.batch_alter_table("qa_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_qa_reports_brief_id"), ["brief_id"], unique=False)

    op.create_table(
        "revisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("brief_id", sa.String(length=36), nullable=False),
        sa.Column("llm_run_id", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["briefs.id"],
            name=op.f("fk_revisions_brief_id_briefs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["llm_run_id"],
            ["llm_runs.id"],
            name=op.f("fk_revisions_llm_run_id_llm_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revisions")),
        sa.UniqueConstraint("brief_id", name=op.f("uq_revisions_brief_id")),
    )
    op.create_table(
        "claim_source_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("evidence_record_id", sa.Integer(), nullable=True),
        sa.Column("external_source_id", sa.String(length=32), nullable=False),
        sa.Column("passage_text", sa.Text(), nullable=True),
        sa.Column("passage_location", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_claim_source_links_claim_id_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_claim_source_links_evidence_record_id_evidence_records"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_source_links")),
        sa.UniqueConstraint(
            "claim_id", "external_source_id", "passage_text", name="uq_claim_source_passage"
        ),
    )
    with op.batch_alter_table("claim_source_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_claim_source_links_claim_id"), ["claim_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_claim_source_links_evidence_record_id"),
            ["evidence_record_id"],
            unique=False,
        )

    op.create_table(
        "qa_findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("qa_report_id", sa.Integer(), nullable=False),
        sa.Column("finding_kind", sa.String(length=32), nullable=False),
        sa.Column("claim_key", sa.String(length=16), nullable=True),
        sa.Column("classification", sa.String(length=32), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("recommended_correction", sa.Text(), nullable=True),
        sa.Column("finding_payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["qa_report_id"],
            ["qa_reports.id"],
            name=op.f("fk_qa_findings_qa_report_id_qa_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_findings")),
    )
    with op.batch_alter_table("qa_findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_qa_findings_qa_report_id"), ["qa_report_id"], unique=False
        )

    op.create_table(
        "revision_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("claim_key", sa.String(length=16), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=True),
        sa.Column("revised_text", sa.Text(), nullable=True),
        sa.Column("original_source_ids", sa.JSON(), nullable=False),
        sa.Column("revised_source_ids", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
            name=op.f("fk_revision_changes_revision_id_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revision_changes")),
    )
    with op.batch_alter_table("revision_changes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_revision_changes_revision_id"), ["revision_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change."""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("revision_changes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_revision_changes_revision_id"))

    op.drop_table("revision_changes")
    with op.batch_alter_table("qa_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_qa_findings_qa_report_id"))

    op.drop_table("qa_findings")
    with op.batch_alter_table("claim_source_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_source_links_evidence_record_id"))
        batch_op.drop_index(batch_op.f("ix_claim_source_links_claim_id"))

    op.drop_table("claim_source_links")
    op.drop_table("revisions")
    with op.batch_alter_table("qa_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_qa_reports_brief_id"))

    op.drop_table("qa_reports")
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_brief_version_id"))

    op.drop_table("claims")
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_searches_brief_id"))

    op.drop_table("searches")
    with op.batch_alter_table("ontology_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ontology_candidates_mapping_id"))

    op.drop_table("ontology_candidates")
    with op.batch_alter_table("llm_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_runs_brief_id"))

    op.drop_table("llm_runs")
    with op.batch_alter_table("exported_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exported_artifacts_brief_id"))

    op.drop_table("exported_artifacts")
    with op.batch_alter_table("brief_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_brief_versions_brief_id"))

    op.drop_table("brief_versions")
    op.drop_table("brief_evidence")
    op.drop_table("trials")
    with op.batch_alter_table("pico_elements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pico_elements_question_id"))

    op.drop_table("pico_elements")
    with op.batch_alter_table("ontology_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ontology_mappings_question_id"))

    op.drop_table("ontology_mappings")
    with op.batch_alter_table("briefs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_briefs_question_id"))

    op.drop_table("briefs")
    op.drop_table("questions")
    op.drop_table("evidence_records")
    # ### end Alembic commands ###
