"""Validated domain models."""

from evidenceforge.models.brief import CodedBrief
from evidenceforge.models.evaluation import (
    BenchmarkQuestion,
    BenchmarkQuestionSet,
    ClaimEvaluation,
    DatasetReviewStatus,
    EvaluationCase,
    EvaluationMetrics,
    EvaluationReport,
    EvaluationRun,
    MappingEvaluation,
    MeanMetric,
    PICOReference,
    QuestionSetReviewStatus,
    RatioMetric,
    RetrievalEvaluation,
    RetrievalPrecisionMetric,
)
from evidenceforge.models.evidence import (
    ClinicalTrialRecord,
    EvidencePage,
    EvidenceQuery,
    EvidenceSource,
    PubMedRecord,
    SearchMetadata,
    TrialLocation,
)
from evidenceforge.models.llm import LLMRunMetadata
from evidenceforge.models.ontology import Mapping, OntologyCandidate, OntologyName
from evidenceforge.models.pico import PICO
from evidenceforge.models.qa import (
    Claim,
    ClaimAssessment,
    ClaimType,
    ConsistencyAssessment,
    DeterministicFinding,
    DeterministicRule,
    EvidencePassage,
    QAReport,
    QAReviewerOutput,
    QASeverity,
    QAStatus,
    RevisedDraftOutput,
    RevisionArtifact,
    RevisionChange,
    SupportClassification,
    SynthesisDraft,
    SynthesisQAResult,
    UntrackedClaimFinding,
)

__all__ = [
    "PICO",
    "BenchmarkQuestion",
    "BenchmarkQuestionSet",
    "Claim",
    "ClaimAssessment",
    "ClaimEvaluation",
    "ClaimType",
    "ClinicalTrialRecord",
    "CodedBrief",
    "ConsistencyAssessment",
    "DatasetReviewStatus",
    "DeterministicFinding",
    "DeterministicRule",
    "EvaluationCase",
    "EvaluationMetrics",
    "EvaluationReport",
    "EvaluationRun",
    "EvidencePage",
    "EvidencePassage",
    "EvidenceQuery",
    "EvidenceSource",
    "LLMRunMetadata",
    "Mapping",
    "MappingEvaluation",
    "MeanMetric",
    "OntologyCandidate",
    "OntologyName",
    "PICOReference",
    "PubMedRecord",
    "QAReport",
    "QAReviewerOutput",
    "QASeverity",
    "QAStatus",
    "QuestionSetReviewStatus",
    "RatioMetric",
    "RetrievalEvaluation",
    "RetrievalPrecisionMetric",
    "RevisedDraftOutput",
    "RevisionArtifact",
    "RevisionChange",
    "SearchMetadata",
    "SupportClassification",
    "SynthesisDraft",
    "SynthesisQAResult",
    "TrialLocation",
    "UntrackedClaimFinding",
]
